version: '3'

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
